[2024-06-20T14:26:38.323+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T14:26:38.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-06-20T14:26:36.062746+00:00 [queued]>
[2024-06-20T14:26:38.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-06-20T14:26:36.062746+00:00 [queued]>
[2024-06-20T14:26:38.352+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-20T14:26:38.360+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-06-20 14:26:36.062746+00:00
[2024-06-20T14:26:38.366+0000] {standard_task_runner.py:63} INFO - Started process 51 to run task
[2024-06-20T14:26:38.370+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-06-20T14:26:36.062746+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpa1cvap2x']
[2024-06-20T14:26:38.375+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask reddit_extraction
[2024-06-20T14:26:38.444+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-06-20T14:26:36.062746+00:00 [running]> on host b98327e542f1
[2024-06-20T14:26:38.539+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T14:26:36.062746+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T14:26:36.062746+00:00'
[2024-06-20T14:26:38.540+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T14:26:38.673+0000] {logging_mixin.py:188} INFO - connected to reddit!
[2024-06-20T14:26:38.823+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T14:26:38.823+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 11, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 29, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 59, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
[2024-06-20T14:26:38.833+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-06-20T14:26:36.062746+00:00, execution_date=20240620T142636, start_date=20240620T142638, end_date=20240620T142638
[2024-06-20T14:26:38.843+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task reddit_extraction (received 401 HTTP response; 51)
[2024-06-20T14:26:38.880+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T14:26:38.895+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T14:26:38.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
